- hosts: all
  become: true

  tasks:
    - name: Install the unzip package
      apt:
        name: unzip
        state: present

    - name: Download and extract Vault in /bin
      unarchive:
        src: https://releases.hashicorp.com/vault/0.10.1/vault_0.10.1_linux_amd64.zip
        dest: /bin/
        remote_src: yes

    - name: Make default config and data directory
      file:
        path: /etc/vault.d/data
        state: directory
        owner: root
        group: root
        mode: 0755
        recurse: yes

    - name: Copy default Vault config file
      copy:
        src: config.json
        dest: /etc/vault.d/config.json
        owner: root
        group: root
        mode: 0644

    - name: Launch Vault
      become: true
      become_user: root
      shell: nohup /bin/vault server -config /etc/vault.d/config.json </dev/null >/dev/null 2>&1 &

    - name: Initialize Vault
      become: true
      become_user: root
      shell: VAULT_ADDR=http://127.0.0.1:8200 /bin/vault operator init
